- name: Creates directory
  file:
    path: /home/hipzi/scripts
    state: directory

- name: Transfer the script mysql
  template: 
    src: templates/mysql-user-db.sh.j2
    dest: /home/hipzi/scripts/mysql-user-db.sh

- name: Execute the script mysql
  command: bash /home/hipzi/scripts/mysql-user-db.sh

- name: Add new zone in firewall
  firewalld:
    zone: mariadb-access
    state: present
    permanent: true

- name: Allow connection from wordpress and database server
  firewalld:
    source: "{{ item }}"
    zone: mariadb-access
    permanent: yes
    state: enabled
  loop:
    - 192.168.1.12
    - 192.168.1.13
    - 192.168.1.15
    - 192.168.1.16
  notify: Reload firewalld  

- name: Open port database to firewalld
  firewalld:
    port: 3306/tcp
    zone: mariadb-access
    permanent: yes
    state: enabled
  notify: Reload firewalld