- name: Creates directory
  file:
    path: /home/hipzi/mysql_exporter
    state: directory

- name: Transfer the script mysql exporter
  template: 
    src: templates/mysql_exporter.sh.j2
    dest: /home/hipzi/mysql_exporter/mysql_exporter.sh

- name: Execute the script mysql exporter
  command: bash /home/hipzi/mysql_exporter/mysql_exporter.sh

- name: Add port (ssh, node exporter, mysql exporter) to firewalld
  firewalld:
    port: 9104/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld