version: "3"

services:
  grafana:
    build: .
    image: grafana:1.0
    container_name: grafana_container
    hostname: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - /home/hipzi/grafana/datasources:/etc/grafana/provisioning/datasources
      - /home/hipzi/grafana/dashboards:/etc/grafana/provisioning/dashboards

networks:
  monitoring-network:
    external: true