- name: install nfs-utils
  yum: 
    name: nfs-utils 
    state: latest

- name: Start NFS and enable it
  service: 
    name: nfs
    state: started 
    enabled: yes

- name: Download wordpress
  get_url:
    url: https://wordpress.org/wordpress-5.7.tar.gz
    dest: /home/hipzi/

- name: Extract wordpress
  unarchive:
    src: /home/hipzi/wordpress-5.7.tar.gz
    dest: /home/hipzi/
    remote_src: yes

- name: Copy script config wordpress
  template:
    src: templates/config-wordpress.sh.j2
    dest: /usr/src/config-wordpress.sh

- name: Execute the config wordpress
  shell: bash /usr/src/config-wordpress.sh

- name: Change owner in mountable directory 
  file:
    path: /home/hipzi/wordpress
    state: directory
    recurse: yes
    owner: '1000'
    group: '1000'
    mode: '0755'    

- name: Remove wordpress.tar.gz
  file:
    path: /home/hipzi/wordpress-5.7.tar.gz
    state: absent

- name: Copy exports file
  template:
    src: templates/exports.j2
    dest: /etc/exports
  register: exports

- name: Kick exportfs if /etc/exports changed
  shell: exportfs -rav
  when: exports.changed
  notify: Reload nfs

- name: Open port (nfs, rpcbind, mountd) to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 2049/tcp
    - 111/tcp
    - 20048/tcp
  notify: Reload firewalld
