version: "3"

services:
  haproxy:
    build: .
    image: haproxy:1.0
    container_name: haproxy_container
    hostname: "haproxy"
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - /home/hipzi/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    extra_hosts:
      - "wordpress-1:192.168.1.12" 
      - "wordpress-2:192.168.1.13"
