- name: Install and Configure NFS Client
  import_tasks: nfs_client.yml

- name: Transfer and execute a docker compose wordpress
  import_tasks: wordpress.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Execute Firewall
  import_tasks: firewall.yml

