- name: install nfs-utils
  yum:
    name: nfs-utils
    state: latest

- name: Transfer directory nginx
  copy:
    src: /home/hipzi/Future/docker/nginx/
    dest: /home/hipzi/nginx/

- name: Create a mountable directory 
  file:
    path: /home/hipzi/nginx/wp-content
    state: directory

- name: Mount an NFS volume
  mount:
    src: 192.168.1.14:/home/hipzi/wp-content
    path: /home/hipzi/nginx/wp-content
    opts: rw,sync
    state: mounted
    fstype: nfs

- name: Open port nfs and rpcbind to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 2049/tcp
    - 111/tcp
  notify: Reload firewalld
