- name: Transfer directory phpfpm
  copy: 
    src: /home/hipzi/Future/docker/phpfpm/
    dest: /home/hipzi/phpfpm/

- name: Execute the docker compose wordpress
  shell:
    chdir: /home/hipzi/phpfpm/
    cmd: docker-compose up -d 

- name: Open port webserver to firewalld
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld
