- name: Transfer directory phpfpm
  copy: 
    src: /home/hipzi/Future/docker/phpfpm/
    dest: /home/hipzi/phpfpm/

- name: Execute the docker compose wordpress
  docker_compose:
    project_src: /home/hipzi/phpfpm/
    state: present

