- name: Creates directory
  file:
    path: /home/hipzi/haproxy
    state: directory

- name: Transfer directory haproxy
  copy: 
    src: /home/hipzi/Future/docker/haproxy/
    dest: /home/hipzi/haproxy/

- name: Execute the docker compose haproxy
  docker_compose:
    project_src: /home/hipzi/haproxy/
    state: present

