- name: Creates directory
  file:
    path: /home/hipzi/grafana
    state: directory

- name: Transfer directory grafana
  copy: 
    src: /home/hipzi/docker/grafana/
    dest: /home/hipzi/grafana/

- name: Execute the docker compose grafana
  shell:
    chdir: /home/hipzi/grafana/
    cmd: docker-compose up -d 

- name: Open port grafana to firewalld
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld