- name: Creates directory
  file:
    path: /home/hipzi/grafana
    state: directory

- name: Transfer directory grafana
  copy: 
    src: /home/hipzi/Future/docker/grafana/
    dest: /home/hipzi/grafana/

- name: Execute the docker compose grafana
  docker_compose:
    project_src: /home/hipzi/grafana/
    state: present
