version: "3"

services:
  webserver:
    build: .
    container_name: wordpress_container
    hostname: "wordpress"
    ports:
      - "80:80"
    volumes:
      - /home/hipzi/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/hipzi/wordpress/wp-content:/var/www/wordpress/wp-content
      - ./www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php.ini:/etc/php7/php.ini
    networks:
      - wordpress-network

networks:
  wordpress-network:

