version: "3"

services:
  phpfpm:
    build: .
    container_name: phpfpm_container
    hostname: "phpfpm"
    volumes:
      - ./www.conf:/etc/php7/php-fpm.d/www.conf
      - ./php.ini:/etc/php7/php.ini
    networks:
      - wordpress-network

  nginx:
    build: /home/hipzi/nginx
    container_name: nginx_container
    hostname: "nginx"
    ports:
      - "80:80"
    volumes:
      - /home/hipzi/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/hipzi/nginx/wp-content:/var/www/wordpress/wp-content      
    networks:
      - wordpress-network

networks:
  wordpress-network:

