- name: Wordpress Installation
  uri:
    url: http://{{ inventory_hostname }}/wp-admin/install.php?step=2
    method: POST
    body_format: form-urlencoded
    body:
      weblog_title: Bismillah
      user_name: admin
      admin_password: admin
      admin_password2: admin
      admin_email: admin@example.com
    timeout: 60
  register: result
  retries: 5
  delay: 5
  until: result.status == 200
