- name: Creates directory
  file:
    path: /home/hipzi/alertmanager
    state: directory

- name: Transfer directory alertmanager
  copy: 
    src: /home/hipzi/Future/docker/alertmanager/
    dest: /home/hipzi/alertmanager/

- name: Execute the docker compose alertmanager
  shell:
    chdir: /home/hipzi/alertmanager/
    cmd: docker-compose up -d --force-recreate  

- name: Add port alertmanager to firewalld
  firewalld:
    port: 9093/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld