- name: Creates directory
  file:
    path: /home/hipzi/alertmanager
    state: directory

- name: Transfer directory alertmanager
  copy: 
    src: /home/hipzi/Future/docker/alertmanager/
    dest: /home/hipzi/alertmanager/

- name: Execute the docker compose alertmanager
  docker_compose:
    project_src: /home/hipzi/alertmanager/
    state: present

