- name: Creates directory
  file:
    path: /home/hipzi/prometheus
    state: directory

- name: Transfer directory prometheus
  copy: 
    src: /home/hipzi/Future/docker/prometheus/
    dest: /home/hipzi/prometheus/

- name: Transfer directory prometheus
  docker_network:
    name: monitoring-network
    
- name: Execute the docker compose prometheus
  shell:
    chdir: /home/hipzi/prometheus/
    cmd: docker-compose up -d --force-recreate  

- name: Open port prometheus to firewalld
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld