version: "3"

services:
  prometheus:
    build: .
    container_name: prometheus_container
    hostname: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - /home/hipzi/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/hipzi/prometheus/rules.yml:/etc/prometheus/rules.yml
