version: "3"

services:
  prometheus:
    build: .
    image: prometheus:1.0
    container_name: prometheus_container
    hostname: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - /home/hipzi/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/hipzi/prometheus/rules.yml:/etc/prometheus/rules.yml
    extra_hosts:
      - "ansiblecontroller:192.168.1.17" 
      - "haproxy-monitoring:192.168.1.11" 
      - "wordpress-1:192.168.1.12" 
      - "wordpress-2:192.168.1.13"
      - "nfs:192.168.1.14" 
      - "mariadb-master:192.168.1.15"
      - "mariadb-slave:192.168.1.16" 
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
