global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_centos'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.13:9100','192.168.1.15:9100','192.168.1.16:9100','192.168.1.17:9100','192.168.1.18:9100','192.168.1.19:9100','192.168.1.23:9100']
  - job_name: 'haproxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.23:8404']
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.17:9104','192.168.1.18:9104']
