groups:
- name: Wordpress Down
  rules:
  - alert: Wordpress Down
    # Condition for alerting
    expr: haproxy_server_status{proxy=~"wordpress",server=~"(wordpress1|wordpress2)"}
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'
