- name: Install pip request
  pip:
    name: requests
    executable: pip3

- name: install docker SDK and docker-compose
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: pip3
  with_items:
    - { name: docker, version: 5.0.0 }
    - { name: docker-compose, version: 1.29.2 }
  notify: upgrade pip
  ignore_errors: true


- name: Add docker compose repo
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  
- name: link docker compose
  file: 
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
