- name: install pip
  yum:
    name: python-pip

- name: Install pip request
  pip:
    name: requests

- name: install docker SDK
  command: pip install docker

- name: Add docker compose repo
  get_url:
    url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  
- name: link docker compose
  file: 
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link