- name: Automation
  hosts: all

- name: SSH
  import_playbook: ssh.yml

- name: Docker
  import_playbook: docker.yml

- name: NFS
  import_playbook: nfs_server.yml

- name: MariaDB
  import_playbook: mariadb.yml
    
- name: Wordpress
  import_playbook: wordpress.yml

- name: HAproxy
  import_playbook: haproxy.yml
  
- name: Node Exporter
  import_playbook: node_exporter.yml  

- name: Monitoring
  import_playbook: monitoring.yml  

- name: Fail2Ban
  import_playbook: fail2ban.yml   