- name: Install and Configure DNS
  hosts: dns
  remote_user: hipzi
  become: yes

  tasks:

    - name: Install DNS (BIND)
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - bind
        - bind-utils

    - name: Start Bind Server and enable it
      service:
        name: named
        state: started
        enabled: yes

    - name: Transfer config named.conf
      copy:
        src: /home/hipzi/ansible/files/named.conf
        dest: /etc/named.conf

    - name: Transfer zone file
      copy:
        src: /home/hipzi/ansible/files/future05.hipzi
        dest: /var/named/future05.hipzi

    - name: Transfer reverse zone file
      copy:
        src: /home/hipzi/ansible/files/1.168.192.in-addr.arpa
        dest: /var/named/1.168.192.in-addr.arpa

    - name: Restart bind server
      service:
        name: named
        state: restarted

