- name: Transfer and execute a docker compose haproxy
  hosts: haproxy
  remote_user: hipzi
  become: yes

  tasks:

    - name: Creates directory
      file:
        path: /home/hipzi/haproxy
        state: directory

    - name: Transfer directory haproxy
      copy: 
        src: /home/hipzi/docker/haproxy/
        dest: /home/hipzi/haproxy/

    - name: Execute the docker compose haproxy
      shell:
        chdir: /home/hipzi/haproxy/
        cmd: docker-compose up -d --force-recreate 
