- name: Transfer and execute a docker compose alertmanager
  hosts: haproxy
  remote_user: hipzi
  become: yes

  tasks:

    - name: Creates directory
      file:
        path: /home/hipzi/alertmanager
        state: directory

    - name: Transfer directory alertmanager
      copy: 
        src: /home/hipzi/docker/alertmanager/
        dest: /home/hipzi/alertmanager/

    - name: Execute the docker compose alertmanager
      shell:
        chdir: /home/hipzi/alertmanager/
        cmd: docker-compose up -d --force-recreate  
