- name: Transfer and execute a docker compose wordpress
  hosts: wordpress
  remote_user: hipzi
  become: yes

  tasks:

    - name: Creates directory
      file:
        path: /home/hipzi/wordpress
        state: directory

    - name: Transfer directory wordpress
      copy: 
        src: /home/hipzi/docker/wordpress/
        dest: /home/hipzi/wordpress/

    - name: Transfer directory nginx
      copy:
        src: /home/hipzi/docker/nginx/
        dest: /home/hipzi/nginx/

    - name: Execute the script config php
      command: bash /home/hipzi/wordpress/config-php.sh

    - name: install nfs-utils
      yum:
        name: nfs-utils
        state: latest

    - name: Create a mountable directory if it does not exist
      file:
        path: /home/hipzi/wordpress/wp-content
        state: directory

    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.1.19:/home/hipzi/wp-content
        path: /home/hipzi/wordpress/wp-content
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs

    - name: Restart docker
      command: systemctl restart docker

    - name: Execute the docker compose wordpress
      shell:
        chdir: /home/hipzi/wordpress/
        cmd: docker-compose up -d --force-recreate 
