- name: Add rules firewall for database server
  hosts: dbservers
  remote_user: hipzi
  become: yes

  tasks:

    - name: Start firewalld and enable it
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add port (ssh, node exporter, mysql exporter) to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 9100/tcp
        - 9104/tcp
      notify: Reload firewalld

    - name: Allow connection from wordpress and database server
      firewalld:
        source: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 192.168.1.15
        - 192.168.1.16
        - 192.168.1.17
        - 192.168.1.18
      notify: Reload firewalld      

  handlers:

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

