- name: Add rules firewall for wordpress server
  hosts: wordpress
  remote_user: hipzi
  become: yes

  tasks:

    - name: Start firewalld and enable it
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add port (ssh, node exporter, webserver, nfs, rpcbind) to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 9100/tcp
        - 80/tcp
        - 2049/tcp
        - 111/tcp
      notify: Reload firewalld

  handlers:

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
