- name: Add rules firewall for ansible server
  hosts: ungrouped
  remote_user: hipzi
  become: yes

  tasks:

    - name: Start firewalld and enable it
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add port ssh and node exporter to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 9100/tcp
      notify: Reload firewalld

  handlers:

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
