- name: Transfer and execute a script firewall for ansible server
  hosts: ungrouped
  remote_user: hipzi
  become: yes

  tasks:

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: install iptables
      yum:
        name: iptables-services

    - name: Start iptables and enable it
      service:
        name: iptables
        state: started
        enabled: yes

    - name: Creates directory
      file:
        path: /home/hipzi/firewall
        state: directory

    - name: Transfer the script firewall 
      copy: 
        src: /home/hipzi/firewall/firewall-ansible.sh
        dest: /home/hipzi/firewall/firewall-ansible.sh

    - name: Execute the script firewall
      shell: bash /home/hipzi/firewall/firewall-ansible.sh

    - name: Save rules iptables
      shell: iptables-save > /etc/sysconfig/iptables
      notify: Restart iptables

  handlers:

    - name: Restart iptables
      service:
        name: iptables
        state: restarted
