- name: Add rules firewall for haprxy and monitoring server
  hosts: haproxy
  remote_user: hipzi
  become: yes

  tasks:

    - name: Start firewalld and enable it
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Add port (ssh, node exporter, haproxy, haproxy stats, prometheus, alertmanager, smtp, grafana) to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 9100/tcp
        - 80/tcp
        - 8404/tcp
        - 9090/tcp
        - 9093/tcp
        - 587/tcp
        - 3000/tcp
      notify: Reload firewalld

  handlers:

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded

