- name: Transfer and execute a script mysql
  hosts: dbservers
  remote_user: hipzi
  become: yes
  vars_files:
    - vars/mysql.yml

  tasks:

    - name: Creates directory
      file:
        path: /home/hipzi/scripts
        state: directory

    - name: Transfer the script mysql
      template: 
        src: templates/mysql-user-db.sh.j2
        dest: /home/hipzi/scripts/mysql-user-db.sh

    - name: Execute the script mysql
      command: bash /home/hipzi/scripts/mysql-user-db.sh
