- name: Configure MySQL Master Slave
  hosts: db_master
  remote_user: hipzi
  become: yes
  vars_files:
    - vars/mysql.yml

  tasks:

    - name: Config MySQL Server Master
      template:
        src: templates/my.cnf.j2
        dest: /etc/my.cnf
      notify: Restart Mariadb

  handlers:

    - name: Restart Mariadb
      service:
        name: mariadb
        state: restarted

- hosts: db_slave
  remote_user: hipzi
  become: yes
  vars_files:
    - vars/mysql.yml

  tasks:

    - name: Config MySQL Server Slave
      template:
        src: templates/my.cnf-slave.j2
        dest: /etc/my.cnf
      notify: Restart Mariadb

    - name: Transfer the script mysql-master-slave
      template:
        src: templates/mysql-master-slave.sh.j2
        dest: /home/hipzi/scripts/mysql-master-slave.sh

    - name: Execute the script mysql-master-slave
      command: bash /home/hipzi/scripts/mysql-master-slave.sh

  handlers:
  
    - name: Restart Mariadb
      service:
        name: mariadb
        state: restarted
